ar_layers: &id001 []
compute_components_flag: false
config_ar: !!python/object:neuralprophet.configure.AR
  ar_layers: *id001
  ar_reg: null
  n_lags: 0
  reg_lambda: null
config_events: null
config_holidays: null
config_lagged_regressors: !!python/object/apply:collections.OrderedDict
- - - VTI_5_days_ago
    - !!python/object:neuralprophet.configure.LaggedRegressor
      as_scalar: true
      lagged_reg_layers: &id002 []
      n_lags: 1
      normalize: auto
      reg_lambda: null
  - - pct_change_5d
    - !!python/object:neuralprophet.configure.LaggedRegressor
      as_scalar: true
      lagged_reg_layers: *id002
      n_lags: 1
      normalize: auto
      reg_lambda: null
  - - TPM_var
    - !!python/object:neuralprophet.configure.LaggedRegressor
      as_scalar: true
      lagged_reg_layers: *id002
      n_lags: 1
      normalize: auto
      reg_lambda: null
  - - TDES_var
    - !!python/object:neuralprophet.configure.LaggedRegressor
      as_scalar: true
      lagged_reg_layers: *id002
      n_lags: 1
      normalize: auto
      reg_lambda: null
  - - IPC_var
    - !!python/object:neuralprophet.configure.LaggedRegressor
      as_scalar: true
      lagged_reg_layers: *id002
      n_lags: 1
      normalize: auto
      reg_lambda: null
  - - BC_var
    - !!python/object:neuralprophet.configure.LaggedRegressor
      as_scalar: true
      lagged_reg_layers: *id002
      n_lags: 1
      normalize: auto
      reg_lambda: null
config_normalization: !!python/object:neuralprophet.configure.Normalization
  global_data_params: !!python/object/apply:collections.OrderedDict
  - - - ds
      - &id004 !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
        - 48902400000000000
        - 10
        shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
        - 1669852800000000000
        - null
        - null
        - 10
    - - y
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - &id003 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          ssh2vp8SUkA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          16NwPQqHZ0A=
    - - VTI_5_days_ago
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          4noUrkfxUUA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          16NwPQqHZ0A=
    - - pct_change_5d
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          wPQ/b0r1IEA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          ayVHe/1TFcA=
    - - TPM_var
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          gZVDi2znyz8=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          gZVDi2zny78=
    - - TDES_var
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          AAAAAAAA2D8=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          6iYxCKwcur8=
    - - IPC_var
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          3Pl+arx0kz8=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          /Knx0k1iYL8=
    - - BC_var
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          rGnecYqO8j8=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id003
        - !!binary |
          MzMzMzMz478=
  global_normalization: true
  global_time_normalization: true
  local_data_params: !!python/object/apply:collections.OrderedDict
  - - - __df__
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - *id004
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                ssh2vp8SUkA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                16NwPQqHZ0A=
          - - VTI_5_days_ago
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                4noUrkfxUUA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                16NwPQqHZ0A=
          - - pct_change_5d
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                wPQ/b0r1IEA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                ayVHe/1TFcA=
          - - TPM_var
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                gZVDi2znyz8=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                gZVDi2zny78=
          - - TDES_var
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                AAAAAAAA2D8=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                6iYxCKwcur8=
          - - IPC_var
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                3Pl+arx0kz8=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                /Knx0k1iYL8=
          - - BC_var
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                rGnecYqO8j8=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id003
              - !!binary |
                MzMzMzMz478=
  normalize: auto
  unknown_data_normalization: false
config_regressors: !!python/object:neuralprophet.configure.ConfigFutureRegressors
  d_hidden: 4
  model: linear
  num_hidden_layers: 2
  regressors: null
config_seasonality: !!python/object:neuralprophet.configure.ConfigSeasonality
  computation: fourier
  condition_name: null
  daily_arg: auto
  daily_global_local: auto
  global_local: global
  mode: additive
  periods: !!python/object/apply:collections.OrderedDict
  - - - weekly
      - !!python/object:neuralprophet.configure.Season
        arg: auto
        condition_name: null
        global_local: global
        period: 7
        resolution: 3
  reg_lambda: 0
  seasonality_local_reg: false
  weekly_arg: auto
  weekly_global_local: auto
  yearly_arg: auto
  yearly_global_local: auto
config_train: !!python/object:neuralprophet.configure.Train
  batch_size: 32
  epochs: 200
  lambda_delay: 100
  learning_rate: 0.01
  loss_func: !!python/object:torch.nn.modules.loss.SmoothL1Loss
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: {}
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: {}
    _non_persistent_buffers_set: !!set {}
    _parameters: {}
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    beta: 0.3
    reduction: none
    training: true
  loss_func_name: SmoothL1Loss
  lr_finder_args: {}
  n_data: 566
  newer_samples_start: 0.0
  newer_samples_weight: 2
  optimizer: !!python/name:torch.optim.adamw.AdamW ''
  optimizer_args:
    weight_decay: 0.001
  quantiles:
  - 0.5
  reg_delay_pct: 0.5
  reg_lambda_trend: null
  scheduler: !!python/name:torch.optim.lr_scheduler.OneCycleLR ''
  scheduler_args:
    anneal_strategy: cos
    div_factor: 10.0
    final_div_factor: 10.0
    pct_start: 0.3
    three_phase: true
  trend_reg_threshold: null
config_trend: !!python/object:neuralprophet.configure.Trend
  changepoints: null
  changepoints_range: 0.8
  growth: linear
  n_changepoints: 20
  trend_global_local: global
  trend_local_reg: false
  trend_reg: 0.0001
  trend_reg_threshold: null
id_list:
- __df__
lagged_reg_layers: *id002
max_lags: 1
meta_used_in_model: false
metrics:
  MAE:
  - MeanAbsoluteError
  - {}
  RMSE:
  - MeanSquaredError
  - squared: false
n_forecasts: 1
n_lags: 0
num_seasonalities_modelled: 1
num_seasonalities_modelled_dict: !!python/object/apply:collections.OrderedDict
- - - yearly
    - 1
  - - weekly
    - 1
  - - daily
    - 1
num_trends_modelled: 1
